"""Planner Agent responsible for goal decomposition and task scheduling."""

from __future__ import annotations

from typing import Any, Dict, List
from pydantic import BaseModel, Field

from ..framework.agent import Agent, AgentResponse
from ..framework.llm_client import LLMClient


class SubTask(BaseModel):
    """Individual sub-task within an agentic plan."""
    step: int
    title: str
    agent: str
    tool: str
    description: str


class ExecutionPlan(BaseModel):
    """Complete decomposed plan generated by PlannerAgent."""
    tasks: List[SubTask] = Field(default_factory=list)


PLANNER_INSTRUCTION = """
You are a Principal AI Systems Planner and Architect.
Your role is to decompose complex, ambiguous user goals into a sequential, actionable execution plan.

Guidelines:
1. Break down the user objective into 3 to 5 coherent sub-tasks.
2. Assign each task to the most appropriate specialized agent:
   - 'Researcher': for data retrieval, market context, or technical documentation.
   - 'Analyst': for quantitative analysis, financial metrics, and code computation.
   - 'Critic': for quality reflection, fact-checking, and evaluation.
3. Specify which tool (e.g. 'web_search', 'calculator', 'python_repl', 'none') is required.
4. Output a clear, structured JSON schema matching ExecutionPlan.
"""


class PlannerAgent(Agent):
    """Decomposes high-level objectives into actionable sub-tasks."""

    def __init__(self, llm_client: LLMClient) -> None:
        super().__init__(
            name="Planner",
            role="AI Systems Planner & Decomposer",
            system_instruction=PLANNER_INSTRUCTION,
            llm_client=llm_client,
            tools=[],
        )

    def generate_plan(self, goal: str) -> ExecutionPlan:
        """Decompose a goal into an ExecutionPlan."""
        prompt = (
            f"Analyze the following user goal and generate an actionable execution plan:\n\n"
            f"Goal: '{goal}'\n\n"
            "Return the plan strictly formatted according to the ExecutionPlan schema."
        )
        response: AgentResponse = self.invoke(
            input_text=prompt,
            response_schema=ExecutionPlan,
        )

        if response.parsed_json and "tasks" in response.parsed_json:
            return ExecutionPlan(**response.parsed_json)

        # Fallback default plan if schema parsing was bypassed
        return ExecutionPlan(
            tasks=[
                SubTask(
                    step=1,
                    title="Information Gathering",
                    agent="Researcher",
                    tool="web_search",
                    description=f"Gather foundational intelligence for: {goal}",
                ),
                SubTask(
                    step=2,
                    title="Quantitative & Analytical Modeling",
                    agent="Analyst",
                    tool="calculator",
                    description="Analyze quantitative parameters, performance benchmarks, and projections.",
                ),
                SubTask(
                    step=3,
                    title="Quality Audit & Reflection",
                    agent="Critic",
                    tool="none",
                    description="Evaluate the intermediate findings for factual rigor and clarity.",
                ),
            ]
        )
